#!/bin/bash

if [ -z "$1" ]; then
    echo "List of running containers:"
    docker ps
    echo " "
    echo "Usage: `basename "$0"` CONTAINER-NAME"
    echo " "
else
    docker exec -it $1 bash -c 'export TERM=xterm && bash'
fi
