#!/bin/bash 

# get lastest OS X helm version from bintray

current_folder=$(pwd)

cd ~/kube-solo/bin

bin_version=$(curl -I https://bintray.com/deis/helm-ci/helm/_latestVersion | grep "Location:" | sed -n 's%.*helm/%%;s%/view.*%%p' )

curl -L "https://dl.bintray.com/deis/helm-ci/helm-$bin_version-darwin-amd64.zip" -o helm.zip

unzip -o helm.zip

rm -f helm.zip

cd $current_folder
